apiVersion: v1
description: Helm chart for cronjob; Argonaut Resource Template (ART)
home: https://argonaut.dev
maintainers:
  - email: dev@argonaut.dev
    name: Argonaut
name: cronjob
version: v0.6.8
appVersion: v0.6.8
sources:
  - https://argonaut.dev
icon: https://raw.githubusercontent.com/argonautdev/public/main/logos/logo-square.png
