{{- $name := include "argonaut-deployment.uname" . -}}
{{- $chartName := .Chart.Name -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}

{{- range $index, $value := .Values.externalServices }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: "{{- .name }}"
  labels:
    heritage: {{ $releaseService | quote }}
    release: {{ $releaseName | quote }}
    chart: {{ $chartName | quote }}
spec:
  hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  ports:
  {{- range .ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      number: {{ .number }}
  {{- end }}
  resolution: {{ .resolution }} # DNS
  location: {{ .location }}
---
{{- $svcName := .name -}}
{{- range .hosts }}
kind: Service
apiVersion: v1
metadata:
 name: {{ $svcName | quote }}
 labels:
    heritage: {{ $releaseService | quote }}
    release: {{ $releaseName | quote }}
    chart: {{ $chartName | quote }}
spec:
 type: ExternalName
 externalName: {{ . }}
---
{{- end }}
{{- end }}

