{{- $name := include "argonaut-deployment.uname" . -}}
{{- $releaseService := .Release.Service | quote -}}
{{- $releaseName := .Release.Name | quote -}}
{{- $chartName := .Chart.Name -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "argonaut-deployment.uname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "argonaut-deployment.uname" . }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    version: {{ .Values.version | default .Release.Revision | quote }}
  annotations:
    {}
spec:
  serviceName: {{ template "argonaut-deployment.uname" . }}
  selector:
    matchLabels:
      app: "{{ template "argonaut-deployment.uname" . }}"
  replicas: {{ .Values.replicas }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  {{- if .Values.persistentStorage }}
  volumeClaimTemplates:
  {{- range $index, $volumeMount := .Values.persistentStorage }}
  - metadata:
      name: "storage-vol-{{ $index }}"
      labels:
        heritage: {{ $releaseService }}
        release: {{ $releaseName }}
        chart: {{ $chartName }}
        app: {{ $name }}
    spec:
      storageClassName: "ebs-gp2-resizable"
      accessModes:
        - {{ $volumeMount.accessMode | quote }}
      resources:
        requests:
          storage: {{ $volumeMount.capacity | quote }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      name: "{{ template "argonaut-deployment.uname" . }}"
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}"
        app: "{{ template "argonaut-deployment.uname" . }}"
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{/* This forces a restart if the configmap has changed */}}
        {{- if .Values.extraConfig }}
        configchecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
        {{- if .Values.fsGroup }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        {{- end }}
      {{- if .Values.rbac.create }}
      serviceAccountName: "{{ template "argonaut-deployment.uname" . }}"
      {{- else if not (eq .Values.rbac.serviceAccountName "") }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if or (eq .Values.antiAffinity "hard") (eq .Values.antiAffinity "soft") .Values.nodeAffinity }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      affinity:
      {{- end }}
      {{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "{{ template "argonaut-deployment.uname" .}}"
            topologyKey: {{ .Values.antiAffinityTopologyKey }}
      {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: {{ .Values.antiAffinityTopologyKey }}
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "{{ template "argonaut-deployment.uname" . }}"
      {{- end }}
      {{- with .Values.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      # Mount Secrets
      volumes:
        {{- range .Values.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
            {{- if .defaultMode }}
            defaultMode: {{ .defaultMode }}
            {{- end }}
        {{- end }}
      # extraConfig
        {{- if .Values.extraConfig }}
        - name: extraconfig
          configMap:
            name: {{ template "argonaut-deployment.uname" . }}-config
        {{- end }}
{{- if .Values.keystore }}
        - name: keystore
          emptyDir: {}
        {{- range .Values.keystore }}
        - name: keystore-{{ .secretName }}
          secret: {{ toYaml . | nindent 12 }}
        {{- end }}
{{ end }}
      {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: {{ template "argonaut-deployment.uname" . }}-img-secret
      initContainers:
      {{- if .Values.initContainer.enabled }}
      - name: init-container
        securityContext:
          # runAsUser: 0
          # privileged: true
        image: "{{ .Values.initContainer.image }}"
        {{- if eq .Values.initContainer.image "latest" }}
        imagePullPolicy: "Always"
        {{- else }}
        imagePullPolicy: "IfNotPresent"
        {{- end }}
        command: {{ .Values.initContainer.command }}
        resources:
{{ toYaml .Values.initResources | indent 10 }}
      {{- end }}
      {{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
      {{- end }}
      containers:
      - name: "{{ template "argonaut-deployment.name" . }}"
        securityContext:
{{ toYaml .Values.securityContext | indent 10 }}
        image: "{{ template "argonaut-deployment.imageName" . }}"
        {{- if eq .Values.imageTag "latest" }}
        imagePullPolicy: "Always"
        {{- else }}
        imagePullPolicy: "IfNotPresent"
        {{- end }}
        ports:
        {{- range .Values.services }}
        - name: "{{ $name | trunc 5 -}}-{{- .name }}"
          containerPort: {{ .port }}
          # protocol: {{ .protocol }}
        {{- end }}
        {{- if .Values.entrypoint }}
        command: {{ .Values.entrypoint }}
        {{- end }}
        {{- if .Values.cmd }}
        args: {{ .Values.cmd }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
{{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 10 }}
{{- end }}
{{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}
{{- end }}
        # Persistence Enabled - volume mounts
        {{- if .Values.persistentStorage }}
        volumeMounts:
          {{- range $index, $volumeMount := .Values.persistentStorage }}
          - name: "storage-vol-{{ $index }}"
            mountPath: "{{ $volumeMount.mountPath }}"
          {{- end }}
        {{- end }}
{{ if .Values.keystore }}
          - name: keystore
            mountPath: /usr/share/"{{ template "argonaut-deployment.uname" . }}"/config/"{{ template "argonaut-deployment.uname" . }}".keystore
            subPath: "{{ template "argonaut-deployment.uname" . }}".keystore
{{ end }}
          {{- range .Values.secretMounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
          {{- range $path, $config := .Values.extraConfig }}
          - name: extraconfig
            mountPath: /usr/share/"{{ template "argonaut-deployment.uname" . }}"/config/{{ $path }}
            subPath: {{ $path }}
          {{- end -}}
        {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
        {{- end }}
{{- if .Values.lifecycle }}
        lifecycle:
{{ toYaml .Values.lifecycle | indent 10 }}
{{- end }}
      {{- if .Values.extraContainers }}
{{ toYaml .Values.extraContainers | indent 6 }}
      {{- end }}
